DROP TABLE IF EXISTS produtoCategoria;
DROP TABLE IF EXISTS Registro;
DROP TABLE IF EXISTS itemVenda;
DROP TABLE IF EXISTS Venda;
DROP TABLE IF EXISTS FormaPag;
DROP TABLE IF EXISTS Promocao;
DROP TABLE IF EXISTS Estoque;
DROP TABLE IF EXISTS Produto;
DROP TABLE IF EXISTS Categoria;
DROP TABLE IF EXISTS Cliente;
DROP TABLE IF EXISTS Funcionario;
DROP TABLE IF EXISTS Fornecedor;
DROP TABLE IF EXISTS Endereco;

DROP VIEW IF EXISTS ProdutosVendidos;
DROP VIEW IF EXISTS FormaPagVendas;
DROP VIEW IF EXISTS ClienteGastoTotal;
DROP VIEW IF EXISTS ProdutoTotalCusto;
DROP VIEW IF EXISTS ClienteGastoMedio;
DROP VIEW IF EXISTS PromocaoAtivaHoje;
DROP VIEW IF EXISTS ClienteUltimaCompra;
DROP VIEW IF EXISTS ProdutosSemEstoque;
DROP VIEW IF EXISTS ProdutosJaVendidos;
DROP VIEW IF EXISTS VendasPendentes;

